BEGIN;

DELETE FROM repinfo WHERE form = 'PSTran';

INSERT INTO repinfo (form,name,type,val,val2,df,df2) VALUES
('PSTran','s_thu_kho','C','Thủ kho                                                         ','Storekeeper                                                     ','Thủ kho                                                         ','Storekeeper                                                     '),
('PSTran','f_ong_ba','F','Ong_ba','Ong_ba','Ong_ba','Ong_ba'),
('PSTran','c_dia_chi','C','Địa chỉ                                                         ','Address                                                         ','Địa chỉ                                                         ','Address                                                         '),
('PSTran','c_dien_giai','C','Diễn giải                                                       ','Description                                                     ','Diễn giải                                                       ','Description                                                     '),
('PSTran','c_kh','C','Đơn vị                                                          ','Company                                                         ','Đơn vị                                                          ','Company                                                         '),
('PSTran','c_ong_ba','C','Người nhận hàng                                                 ','Receiver                                                        ','Người nhận hàng                                                 ','Receiver                                                        '),
('PSTran','f_dien_giai','F','Dien_giai                                                       ','Dien_giai                                                       ','Dien_giai                                                       ','Dien_giai                                                       '),
('PSTran','f_tk_no','F','Ma_nx                                                           ','Ma_nx                                                           ','Ma_nx                                                           ','Ma_nx                                                           '),
('PSTran','h_dvt','C','Đvt                                                             ','Uom                                                             ','Đvt                                                             ','Uom                                                             '),
('PSTran','h_gia','C','Giá                                                             ','Price                                                           ','Giá                                                             ','Price                                                           '),
('PSTran','h_ma_kho','C','Kho                                                             ','Site                                                            ','Kho                                                             ','Site                                                            '),
('PSTran','h_ma_vt','C','Mã vt                                                           ','Item id                                                         ','Mã vt                                                           ','Item id                                                         '),
('PSTran','h_so_luong','C','Sl                                                              ','Q.ty                                                            ','Sl                                                              ','Q.ty                                                            '),
('PSTran','h_stt','C','Tt                                                              ','No                                                              ','Tt                                                              ','No                                                              '),
('PSTran','h_ten_vt','C','Tên vật tư                                                      ','Item name                                                       ','Tên vật tư                                                      ','Item name                                                       '),
('PSTran','h_tien','C','Tiền                                                            ','Amount                                                          ','Tiền                                                            ','Amount                                                          '),
('PSTran','h_tk_co','C','Tk có                                                           ','Cr                                                              ','Tk có                                                           ','Cr                                                              '),
('PSTran','h_tk_no','C','Mã nx                                                           ','Reason                                                          ','Mã nx                                                           ','Reason                                                          '),
('PSTran','s_Amount','C','Tiền hàng                                                       ','Amount                                                          ','Tiền hàng                                                       ','Amount                                                          '),
('PSTran','s_giao_hang','C','Người giao hàng                                                 ','Receiver                                                        ','Người giao hàng                                                 ','Receiver                                                        '),
('PSTran','s_nhan_hang','C','Người xuất                                                      ','Deliverer                                                       ','Người xuất                                                      ','Deliverer                                                       '),
('PSTran','s_nhap_hang','C','Pt xuất hàng                                                    ','Admin                                                           ','Pt xuất hàng                                                    ','Admin                                                           '),
('PSTran','s_Tax','C','Thuế                                                            ','Tax                                                             ','Thuế                                                            ','Tax                                                             '),
('PSTran','s_total','C','Tổng cộng                                                       ','Total                                                           ','Tổng cộng                                                       ','Total                                                           '),
('PSTran','h_nguoi_lap','C','Người lập biểu','Creator','Tổng cộng                                                       ','Total                                                           '),
('PSTran','h_ck','C','Chiết khấu','Discount','Tổng cộng                                                       ','Total                                                           '),
('PSTran','h_nguoi_nhan','C','Người nhận hàng','Receipter','Tổng cộng                                                       ','Total                                                           '),
('PSTran','h_seri','C','Số serial','Serial number','Tổng cộng                                                       ','Total                                                           '),
('PSTran','h_po_khsx','C','PO KHSX','PO KHSX','PO KHSX','PO KHSX'),
('PSTran','h_dau_tuan','C','Dấu tuần','Dấu tuần','Dấu tuần','Dấu tuần');

COMMIT;
