BEGIN;

DELETE FROM vouchergridinfo WHERE vcode = 'TK1';

INSERT INTO vouchergridinfo (vcode,gridid,fieldname,fieldposition,fieldcaption,fieldcaption2,carry,visible,editable,style,width,lookupid,lookupfieldname,notempty) VALUES
('TK1','cttksx','dau_tuan','4','Dấu tuần','Dấu tuần','0','1','0','MA','100','','','0'),
('TK1','cttksx','so_lan_hong_may','0','Số lần hỏng máy','Số lần hỏng máy','0','0','0','SL','120','','','0'),
('TK1','cttksx','tg_cho_nvl','0','TG chờ NVL(Giây)','TG chờ NVL(Giây)','0','0','0','SL','120','','','0'),
('TK1','cttksx','so_lan_cho_mau','0','Số lần chờ mẫu','Số lần chờ mẫu','0','0','0','SL','120','','','0'),
('TK1','cttksx','tg_cho_mau','0','TG Chờ mẫu(Giây)','TG Chờ mẫu(Giây)','0','0','0','SL','120','','','0'),
('TK1','cttksx','tg_hong_may','0','TG hỏng máy(Giây)','TG hỏng máy(Giây)','0','0','0','SL','120','','','0'),
('TK1','cttksx','tg_chinh_may','0','TG Chỉnh máy(Giây)','TG Chỉnh máy(Giây)','0','0','0','SL','120','','','0'),
('TK1','cttksx','so_luong_le_hong','0','KL lề sai hỏng(Kg)','KL lề sai hỏng(Kg)','0','0','0','SL','120','','','0'),
('TK1','cttksx','ma_vt','1','Mã Sp','Item ID','0','1','0','MA','100','','','1'),
('TK1','cttksx','ten_vt','2','Tên sản phẩm','Item Name','0','1','1','TEN','200','','','0'),
('TK1','cttksx','so_dh','0','Số đh','Orders number','0','0','1','MA','100','','','0'),
('TK1','cttksx','ty_le_hong','12','Tỷ lệ hỏng','Weigth','0','1','0','HE_SO','100','','','0'),
('TK1','cttksx','starttime','0','Giờ bắt đầu','%Disc','0','0','0','TIME','100','','','0'),
('TK1','cttksx','endtime','0','Giờ kết thúc','Tax code','0','0','0','TIME','100','','','0'),
('TK1','cttksx','ma_vv','19','Mã vv','Mã vv','0','1','0','MA','100','dmvv','','0'),
('TK1','cttksx','so_ct_kh1','16','Mã kế hoạch','Mã kế hoạch','0','1','1','MA','100','','','0'),
('TK1','cttksx','so_luong_tk','9','SL thống kê','Complete','0','1','0','SL','120','','','0'),
('TK1','cttksx','thong_ke_loi','0','Thống kê lỗi','Statistics error','0','0','0','','100','','','0'),
('TK1','cttksx','so_ct_tk1','0','Phiếu thống kê','Phiếu thống kê','0','0','1','MA','100','','','0'),
('TK1','cttksx','so_ct_pd1','20','Số LSX','Số LSX','0','1','1','MA','100','','','0'),
('TK1','cttksx','so_ct_rew','0','Phiếu Rework','Phiếu Rework','0','0','1','MA','100','','','0'),
('TK1','cttksx','sl_ton_cdsx','0','Tồn cđsx','N cdsx','0','0','1','SL','100','','','0'),
('TK1','cttksx','sl_ton_cdsx_kk','0','Tồn cđsx kiểm kê','Surveys inventory','0','0','0','SL','100','','','0'),
('TK1','cttksx','t_dinh_muc_sai_hong','0','Định mức sai hỏng','Định mức sai hỏng','0','0','1','HE_SO','100','','','0'),
('TK1','cttksx','so_lan_cho_khac','0','Số lần mất điện, khác','Số lần mất điện, khác','0','0','0','SL','120','','','0'),
('TK1','cttksx','so_luong_hong_sx','0','Số lượng hỏng – sản xuất','Fail','0','0','0','SL','120','','','0'),
('TK1','cttksx','so_luong_bu_hao','0','Số lượng hỏng bù hao','Fail','0','0','0','SL','120','','','0'),
('TK1','cttksx','gio_bd_tt','0','Giờ bắt đầu thực tế','Giờ bắt đầu thực tế','0','0','1','TIME','100','','','0'),
('TK1','cttksx','ngay_kt_tt','0','Ngày kết thúc thực tế','Ngày kết thức thực tế','0','0','1','DATE','100','','','0'),
('TK1','cttksx','gio_kt_tt','0','Giờ kết thúc thực tế','Giờ kết thúc thực tế','0','0','1','TIME','100','','','0'),
('TK1','cttksx','sl_dem_tt','0','Số lượng đếm thực tế','Số lượng đếm thực tế','0','0','1','SL','100','','','0'),
('TK1','cttksx','so_luong_tt','0','Số lượng thực tế','Số lượng thực tế','0','0','1','SL','100','','','0'),
('TK1','cttksx','so_luong_test','0','Số lượng test','Số lượng test','0','0','1','SL','100','','','0'),
('TK1','cttksx','tg_cnvl_tt','0','Thời gian chờ khác (giây)','Thời gian chờ khác (giây)','0','0','1','SL','100','','','0'),
('TK1','cttksx','so_lan_cnvl_tt','0','Số lần chờ NVL','số lần chờ NVL','0','0','1','','70','','','0'),
('TK1','cttksx','so_lan_sua_chua_tt','0','Số lần sửa chữa','','0','0','1','','70','','','0'),
('TK1','cttksx','tg_sua_chua_tt','0','Thời gian sửa chữa (giây)','','0','0','1','SL','100','','','0'),
('TK1','cttksx','he_so1','0','Số bát xén','Number bowl Trimmers','0','0','1','SL','100','','','0'),
('TK1','cttksx','dvt','7','Đvt','Unit','0','1','0','DVT','50','','','0'),
('TK1','cttksx','so_lan_cho_mau_tt','0','Số lần chờ mẫu','','0','0','1','','70','','','0'),
('TK1','cttksx','tg_cho_mau_tt','0','Thời gian chờ mẫu (giây)','','0','0','1','SL','100','','','0'),
('TK1','cttksx','tg_dung_khac_tt','0','Thời gian dừng khác (giây)','','0','0','1','SL','100','','','0'),
('TK1','cttksxloi2','ma_nh_loi','7','Nhóm lỗi','Nhóm lỗi','0','0','0','MA','80','','','0'),
('TK1','cttksxloi2','ten_nh','8','Tên nhóm lỗi','Tên nhóm lỗi','0','0','1','TEN','150','','','0'),
('TK1','cttksx','so_luong_bu_hao_pd1','0','Số lượng bù hao (Pcs)','Fail','0','0','1','SL','120','','','0'),
('TK1','cttksx','ngay_bd_tt','0','Ngày bắt đầu thực tế','Ngày bắt đầu thực tế','0','0','1','DATE','100','','','0'),
('TK1','cttksx','so_lan_dung_khac_tt','0','Số lần dừng khác','','0','0','1','','70','','','0'),
('TK1','cttksxloivt','dvt','3','Đvt','Item Name','0','1','1','','200','','','0'),
('TK1','cttksxloivt','ma_kho','4','Mã kho','Item Name','0','1','1','MA','200','','','0'),
('TK1','cttksx2','cong_suat','0','Công suất','Công suất','0','0','1','SL','100','','','0'),
('TK1','cttksx2','ma_bp','5','Mã tổ sx','Dept id','0','1','0','MA','100','','','1'),
('TK1','cttksx2','ma_thao_tac','3','Mã công đoạn sx','Code stages','0','1','0','MA','100','','','1'),
('TK1','cttksx2','ma_vt_item','2','Mã sản phẩm','Item ID','0','1','0','MA','100','','','1'),
('TK1','cttksx2','res_id','0','Mã máy','Mã máy','0','0','0','MA','100','','','0'),
('TK1','cttksx2','stt','1','Stt','.No','0','1','0','','50','','','1'),
('TK1','cttksx2','ten_bp','6','Tên tổ sx','Dept name','0','1','1','','150','','','0'),
('TK1','cttksx2','ten_res','0','Tên máy','Tên máy','0','0','1','','150','','','0'),
('TK1','cttksx2','ten_thao_tac','4','Tên công đoạn sx','Progress stage','0','1','1','','150','','','0'),
('TK1','cttksx2','tg_thay_bai','0','Thời gian thay bài (giây)','Thời gian thay bài (giây)','0','0','1','SL','125','','','0'),
('TK1','cttksxloi','dvt','3','Dvt','Uom','0','1','0','DVT','50','','','0'),
('TK1','cttksxloi','ma_loi','5','Mã lỗi','NG id','0','1','0','MA','80','','','0'),
('TK1','cttksxloi','ma_vt','1','Mã hàng','Item ID','0','1','0','MA','100','','','0'),
('TK1','cttksxloi','ten_vt','2','Tên hàng','Item Name','0','0','1','TEN','200','','','0'),
('TK1','cttksxloi2','dvt','3','Dvt','Uom','0','1','0','DVT','50','','','0'),
('TK1','cttksxloi2','ma_loi','5','Mã lỗi','NG id','0','1','0','MA','80','','','0'),
('TK1','cttksxloi','ten_loi','6','Tên lỗi','NG name','0','0','1','TEN','150','','','0'),
('TK1','cttksxloi2','ma_vt','1','Mã hàng','Item ID','0','1','0','MA','100','','','0'),
('TK1','cttksxloi2','ten_loi','6','Tên lỗi','NG name','0','1','1','TEN','150','','','0'),
('TK1','cttksxloi2','ten_vt','2','Tên hàng','Item Name','0','1','1','TEN','200','','','0'),
('TK1','cttksxnv','so_luong_tg','5','Số giờ thực hiện','SL thêm giờ','0','1','0','SL','100','','','0'),
('TK1','cttksxloivt','ten_vt','2','Tên hàng','Item Name','0','1','1','TEN','200','','','0'),
('TK1','cttksxloivt','ghi_chu','7','Ghi chú','Note','0','1','1','','200','','','0'),
('TK1','cttksxloivt','so_luong','5','SL định mức','Uom','0','1','1','SL','100','','','0'),
('TK1','cttksxloivt','ma_vt','1','Mã hàng','Item ID','0','1','0','MA','100','','','0'),
('TK1','cttksxloivt','ma_vv','8','Mã v/v','Item ID','0','1','1','MA','100','','','0'),
('TK1','cttksxnv','ma_vt','1','Mã SP','Mã nv','0','1','0','MA','100','','','0'),
('TK1','cttksxloi2','so_luong_hong','9','SL hỏng','NG quantities','0','1','0','SL','100','','','0'),
('TK1','cttksxloi','so_luong_hong','7','SL hỏng ','NG quantities','0','1','0','SL','100','','','0'),
('TK1','cttksxnv','ten_vt','2','Tên SP','Tên nv','0','1','0','TEN','200','','','0'),
('TK1','cttksxnv','ma_nv','3','Mã NV','SL hoàn thành','0','1','0','MA','100','','','0'),
('TK1','cttksxnv','ten_nv','4','Tên NV','Làm CN','0','1','0','TEN','200','','','0'),
('TK1','cttksxnv','so_luong','6','Số lương SP','SL hỏng','0','1','0','SL','100','','','0'),
('TK1','cttksxloivt','so_luong_hong','6','SL hỏng ','NG quantities','0','1','0','SL','100','','','0'),
('TK1','cttksx','tg_cho_khac','0','TG mất điện, khác(Giây)','TG mất điện, khác(Giây)','0','0','0','SL','130','','','0'),
('TK1','cttksx','so_luong_le','0','KL lề kỹ thuật(Kg)','KL lề kỹ thuật(Kg)','0','0','0','SL','120','','','0'),
('TK1','cttksx','ghi_chu','18','Ghi chú','Ghi chú','0','1','0','','200','','','0'),
('TK1','cttksx','so_lan_thay_bai','0','Số lần thay bài','Số lần thay bài','0','0','0','SL','120','','','0'),
('TK1','cttksx','tg_thay_bai','0','Thay bài(Giây)','Thay bài(Giây)','0','0','0','SL','120','','','0'),
('TK1','cttksx','so_lan_cho_nvl','0','Số lần chờ NVL','Số lần chờ NVL','0','0','0','SL','120','','','0'),
('TK1','cttksx','ma_version','0','Version','Version','0','0','1','','80','','','0'),
('TK1','cttksx','so_luong_rew','0','SL Rework','Complete','0','0','1','SL','100','','','0'),
('TK1','cttksx','so_luong_pd1','0','SL lượng SX','Complete','0','0','0','SL','120','','','0'),
('TK1','cttksx','model','0','Model','Model','0','0','1','','80','','','0'),
('TK1','cttksx','so_luong_tk1','0','SL hoàn thành(Đvt2)','Complete','0','0','0','SL','120','','','0'),
('TK1','cttksx','so_luong1','0','SL đạt(Đvt2)','Complete','0','0','0','SL','120','','','0'),
('TK1','cttksx','so_luong_bu_hao1_pd1','0','Số lượng bù hao (Đvt2)','Fail','0','0','1','SL','120','','','0'),
('TK1','cttksx','ngay_hoan_thanh','8','Ngày YC hoàn thành','Date','0','1','0','DATE','100','','','0'),
('TK1','cttksx','so_luong_hong1','0','SL hỏng (Đvt2)','Fail','0','0','0','SL','120','','','0'),
('TK1','cttksx','so_luong_pd1b','0','SL lượng(Đvt2) SX','Complete','0','0','1','SL','120','','','0'),
('TK1','cttksx','ma_kho','6','Mã kho','Shifts','0','1','0','MA','100','dmkho','','0'),
('TK1','cttksx','so_luong','10','SL đạt','Complete','0','1','0','SL','120','','','0'),
('TK1','cttksx','so_luong_hong','11','SL hỏng','Fail','0','1','1','SL','120','','','0'),
('TK1','cttksx','ma_thao_tac_truoc','17','Mã công đoạn sản xuất trước','Mã công đoạn sản xuất trước','0','1','1','MA','100','','','0'),
('TK1','cttksx','po_khsx','3','PO KHSX','PO KHSX','0','1','0','MA','100','','','1'),
('TK1','cttksx','ng_by_ns','13','NG do Ngọc Sơn','NG do Ngọc Sơn','0','1','0','SL','100','','','0'),
('TK1','cttksx','ng_by_ncc','14','NG do nhà cung cấp','NG do nhà cung cấp','0','1','0','SL','100','','','0');

COMMIT;
