

----------[message]--------

BEGIN;

DELETE FROM message WHERE form in ('INTrans');

INSERT INTO message (form,mess_id,mess_text,mess_text2,df,df2) VALUES
('INTrans','021','Địa chỉ GH','Shipping address','Địa chỉ GH','Shipping address'),
('INTrans','943','Mã giao dịch','Trading code','Đơn giá','Đơn giá'),
('INTrans','944','Tên khách hàng','Customer name','Đơn giá','Đơn giá'),
('INTrans','945','Điện thoại','Phone number','Đơn giá','Đơn giá'),
('INTrans','946','Mã nvgh','Shipper','Đơn giá','Đơn giá'),
('INTrans','947','Mã loại PT','Vehicle type','Đơn giá','Đơn giá'),
('INTrans','948','Mã phương tiện','Vehicle id','Đơn giá','Đơn giá'),
('INTrans','949','Diễn giải','Note','Đơn giá','Đơn giá'),
('INTrans','950','Số phiếu YC đổi hàng bán','Bartering of votes required to sell','Đơn giá','Đơn giá'),
('INTrans','951','Số phiếu YC đổi hàng mua','Bartering of votes required to buy','Đơn giá','Đơn giá'),
('INTrans','952','Mã hàng','Item name','Đơn giá','Đơn giá'),
('INTrans','953','Trạng thái','Status','Đơn giá','Đơn giá'),
('INTrans','954','Điều kiện lọc','Data filter','Đơn giá','Đơn giá'),
('INTrans','910','Mã loại PT','Vehicle type','&Quay ra','&Close'),
('INTrans','913','Số chuyến','Number of flight','&Quay ra','&Close'),
('INTrans','915','Diễn giải','Note','&Quay ra','&Close'),
('INTrans','500','In chứng từ','Print','In chứng từ','Print'),
('INTrans','501','Tiêu đề','Title','Tiêu đề','Title'),
('INTrans','502','Số liên','Number of copies','Số liên','Number of copies'),
('INTrans','503','Số chứng từ gốc','Include number of docs','Số chứng từ gốc','Include number of docs'),
('INTrans','504','Mẫu báo cáo','Report form','Mẫu báo cáo','Report form'),
('INTrans','505','&In','&Print','&In','&Print'),
('INTrans','506','&Xem','&View','&Xem','&View'),
('INTrans','507','&Quay ra','&Close','&Quay ra','&Close'),
('INTrans','401','Ngày {0} tháng {1} năm {2}','Date {0} Month {1} Year {2}','Ngày {0} tháng {1} năm {2}','Date {0} Month {1} Year {2}'),
('INTrans','402','Số phiếu: {0}','Voucher No: {0}','Số phiếu: {0}','Voucher No: {0}'),
('INTrans','403','Bằng chữ: {0} đồng chẵn','In words {0}','Bằng chữ: {0} đồng chẵn','In words {0}'),
('INTrans','100','Điều kiện lọc','Filter','Điều kiện lọc),
(','Filter'),
('INTrans','101','Số chứng từ','Vo. No From','Số chứng từ),
(','Vo. No From),
('),
('INTrans','102','Ngày chứng từ','Date From','Số chứng từ),
(','Vo. No From),
('),
('INTrans','103','Số đơn hàng','Order no','Số chứng từ),
(','Vo. No From),
('),
('INTrans','104','Mã khách hàng','Custom ID','Số chứng từ),
(','Vo. No From),
('),
('INTrans','116','&Nhận','&Ok','Số chứng từ),
(','Vo. No From),
('),
('INTrans','117','&Hủy','&Cancel','Số chứng từ),
(','Vo. No From),
('),
('INTrans','119','*,* - Tất cả;0,0 - Chưa chuyển vào SC;1,1 - Đã chuyển vào SC','*,* - All;0,0 - Hold;1,1 - Posted','*,* - Tất cả;0,0 - Chưa chuyển vào SC;1,1 - Đã chuyển vào SC','*,* - All;0,0 - Hold;1,1 - Posted'),
('INTrans','114','Lọc theo NSD (0/1)','Filter by user (0/1)','Lọc theo NSD (0/1)','Filter by user (0/1)'),
('INTrans','018','Giờ nhận hàng','Ngày nhận hàng','&Quay ra','&Close'),
('INTrans','017','Ngày nhận','Ngày nhận','&Quay ra','&Close'),
('INTrans','019','Ngày giao','Ngày giao','&Quay ra','&Close'),
('INTrans','020','Giờ giao','Giờ giao','&Quay ra','&Close'),
('INTrans','015','NV Giao hàng','Delivery person','&Quay ra','&Close'),
('INTrans','909','Giờ giao hàng','Delivery time','&Quay ra','&Close'),
('INTrans','911','Mã phương tiện','Vehicle id','&Quay ra','&Close'),
('INTrans','912','Số km','Mileage','&Quay ra','&Close'),
('INTrans','914','Nhân viên GH','Shipper','&Quay ra','&Close'),
('INTrans','901','Thông tin chính','Main infomation','&Quay ra','&Close'),
('INTrans','903','Mã khách hàng','Customer id','&Quay ra','&Close'),
('INTrans','904','Địa chỉ','Address','&Quay ra','&Close'),
('INTrans','905','Điện thoại','Telephone num','&Quay ra','&Close'),
('INTrans','906','TP/Tỉnh','City / Province','&Quay ra','&Close'),
('INTrans','907','Quận/Huyện','District','&Quay ra','&Close'),
('INTrans','908','Ngày GH','Delivery date','&Quay ra','&Close'),
('INTrans','916','Mã đvcs','Unit','&Quay ra','&Close'),
('INTrans','917','Số ct','Voucher id','&Quay ra','&Close'),
('INTrans','918','Ngày lập ct','Order date','&Quay ra','&Close'),
('INTrans','919','Ngày ct','Vourcher date','&Quay ra','&Close'),
('INTrans','920','Thu tiền giao hàng','Delivery levy','&Quay ra','&Close'),
('INTrans','921','Còn phải thu','Receivable amount','&Quay ra','&Close'),
('INTrans','922','Tiền thu (F12)','Proceeds ( F12 )','&Quay ra','&Close'),
('INTrans','923','Chi tiết','Detail','&Quay ra','&Close'),
('INTrans','924','Dịch vụ','Service','&Quay ra','&Close'),
('INTrans','925','Số đh','Order id','&Quay ra','&Close'),
('INTrans','926','Số lệnh vc','Ship order id','&Quay ra','&Close'),
('INTrans','927','Tổng tiền hàng','Total amount','&Quay ra','&Close'),
('INTrans','928','Đã thanh toán','Paid','&Quay ra','&Close'),
('INTrans','929','Tiền trả sau','Pay later','&Quay ra','&Close'),
('INTrans','930','Thông tin khác','Orther','&Quay ra','&Close'),
('INTrans','932','Đơn giá','Price','&Quay ra','&Close'),
('INTrans','931','Nhân viên BH','Saler id','&Quay ra','&Close'),
('INTrans','934','Chiết khấu','Discount','&Quay ra','&Close'),
('INTrans','935','Tiền thuế','Tax amount','&Quay ra','&Close'),
('INTrans','936','Giá {0}','Price','&Quay ra','&Close'),
('INTrans','937','Chiết khấu {0}','Discount','&Quay ra','&Close'),
('INTrans','938','Thuế {0}','Tax amount','&Quay ra','&Close'),
('INTrans','939','Mã đvcs','Unit','&Quay ra','&Close'),
('INTrans','940','Số chứng từ','Voucher id','&Quay ra','940'),
('INTrans','933','Thành tiền','Amount','&Quay ra','&Close'),
('INTrans','941','Số lệnh vc từ số/đến','Shipping order id from / to','&Quay ra','940'),
('INTrans','942','Số đơn hàng','Order Number','&Quay ra','940'),
('INTrans','955','Giá trị mặc định','Default values','Đơn giá','Đơn giá'),
('INTrans','956','Kho nhập','Import inventory','Đơn giá','Đơn giá'),
('INTrans','957','Từ ngày','Date from','Đơn giá','Đơn giá'),
('INTrans','960','Đơn giá','Đơn giá','Đơn giá','Đơn giá'),
('INTrans','959','Số ECIS ','Số ECIS ','Số ECIS ','Số ECIS '),
('INTrans','902','Loại lệnh vc','Type of shipping','Loại lệnh vc','&Close'),
('INTrans','010','Tổng cộng','Total','Tổng cộng','Total'),
('INTrans','511','Tạo mẫu Import','Prototyping Import','Tạo mẫu Import','Prototyping Import'),
('INTrans','509','Loại DO','type DO','Loại DO','type DO'),
('INTrans','508','1 – DO Plan, 2 – Do Unplan, 3 – DO RMA','1 – DO Plan, 2 – Do Unplan, 3 – DO RMA','1 – DO Plan, 2 – Do Unplan, 3 – DO RMA','1 – DO Plan, 2 – Do Unplan, 3 – DO RMA'),
('INTrans','512','Import DO','Import DO','Import DO','Import DO'),
('INTrans','510','Lịch giao hàng','Delivery schedules','Lịch giao hàng','Delivery schedules'),
('INTrans','513','Import DO Sam Sung','Import DO Sam Sung','Import DO Sam Sung','Import DO Sam Sung'),
('INTrans','016','NV Nhận hàng','Receipt person','&Quay ra','&Close'),
('INTrans','105','Người lập','Người lập','Người lập',''),
('INTrans','900','Lịch đóng cont','Orders shipping','Lịch đóng cont','&Close'),
('INTrans','011','Tồng số pallet','Total','Tồng số pallet','Total'),
('INTrans','012','Tông số kiện','Total','Tông số kiện','Total'),
('INTrans','707','Tỷ giá','Tỷ giá','Tỷ giá','Tỷ giá'),
('INTrans','963','Tiền {0}','Price','Tiền {0}','&Close'),
('INTrans','962','Giá {0}','Price','Giá {0}','&Close'),
('INTrans','958','Mã nơi nhận','Mã nơi nhận','Mã nơi nhận','Mã nơi nhận'),
('INTrans','M50','0,0 – Dự kiến; 1,1 – Chính thức','0,0 – Dự kiến; 1,1 – Chính thức','0,0 – Dự kiến; 1,1 – Chính thức','0,0 – Dự kiến; 1,1 – Chính thức'),
('INTrans','M51','Tình trạng','Status no','Tình trạng','Status no'),
('INTrans','M52','Tìm kiếm số ECIS','Search','Tìm kiếm số ECIS','Search'),
('INTrans','M54','Ngày xuất hàng','Date no','Ngày xuất hàng','Date no');

COMMIT;