BEGIN;

DELETE FROM vouchergridinfo WHERE vcode = 'QC1';

INSERT INTO vouchergridinfo (vcode,gridid,fieldname,fieldposition,fieldcaption,fieldcaption2,carry,visible,editable,style,width,lookupid,lookupfieldname,notempty) VALUES
('QC1','ctqc','so_luong_nhap','9','Số lượng nhập','Số lượng nhập','0','0','0','SL','80','','','0'),
('QC1','ctqc','ten_vt','4','Tên VT','Tên VT','0','1','1','','200','','','0'),
('QC1','ctqc','so_dh','1','Số đh','Cr Account','0','1','0','','120','','','0'),
('QC1','ctqc','ma_lo','2','Mã lô','BatchID','0','0','0','MA','80','','','0'),
('QC1','ctqc','ma_vt','3','Mã VT','Mã VT','0','1','0','MA','100','','','0'),
('QC1','ctqc','so_luong_hong','17','Số lượng NG','Số lượng NG','0','1','1','SL','80','','','0'),
('QC1','ctqc','ngay_hhsd','19','Ngày HHSD','Date End','0','0','0','DATE','100','','','0'),
('QC1','ctqc','ma_loi','15','Mã lỗi','Err ID','0','0','0','','80','','','0'),
('QC1','ctqc','ok_yn','16','Đạt','Achieve','0','0','0','CHECKBOX','40','','','0'),
('QC1','ctqc','ty_le_hong','18','Tỷ lệ hỏng','Tỷ lệ hỏng','0','0','1','TY_GIA','80','','','0'),
('QC1','ctqc','so_luong_qc','11','Số lượng kiểm tra','Số lượng kiểm tra','0','1','0','SL','80','','','0'),
('QC1','ctloqc1','ma_lo','2','Mã lô','Seri number','0','1','1','TEN','100','','','0'),
('QC1','ctloqc1','ma_vt','0','Mã Vt','Item ID','0','1','1','MA','100','dmvt','ten_vt','1'),
('QC1','ctloqc1','ten_vt','1','Tên vật tư','Item Name','0','1','1','TEN','180','','','0'),
('QC1','ctloqc1','so_luong','8','Số lượng','Quantity','0','1','1','SL','80','','','0'),
('QC1','ctloqc1','sl_ok','9','Số lượng OK','Quantity OK','0','1','1','SL','80','','','0'),
('QC1','ctloqc1','sl_ng','10','Số lượng NG','Quantity NG','0','1','1','SL','80','','','0'),
('QC1','ctloqc1','ket_qua_qc','11','Kết luận','Results QC','0','1','1','COMBOBOX','160','','','0'),
('QC1','ctloqc1','sl_nhap','12','SL cho phép nhập','SL cho phép nhập','0','1','1','SL','80','','','0'),
('QC1','ctloqc1','sl_tra','13','SL trả về','SL trả về','0','1','1','SL','80','','','0'),
('QC1','ctloqc1','ngay_hhsd','7','Hạn dùng','Hạn dùng','0','1','1','DATE','80','','','0'),
('QC1','ctloqc1','ma_kho','3','Mã kho','Stock ID','0','1','1','MA','100','','','0'),
('QC1','ctqc','so_luong_qc2','12','Số lượng kiểm tra (Đvt2)','Số lượng kiểm tra (Tờ)','0','0','0','SL','100','','','0'),
('QC1','ctqc','so_luong_nhap1','10','Số lượng nhập (Đvt2)','Số lượng nhập (Tờ)','0','0','1','SL','100','','','0'),
('QC1','ctqc','dvt','7','ĐVT','ĐVT','0','1','0','MA','60','','','0'),
('QC1','ctqc','ma_kho','8','Mã kho','Mã kho','1','1','0','MA','80','','','0'),
('QC1','ctqc','so_luong_qc1','13','Số lượng kiểm tra chọn mẫu','Số lượng kiểm tra chọn mẫu','0','0','0','SL','80','','','0'),
('QC1','ctqc','so_luong','14','Số lượng OK','Số lượng OK','0','1','0','SL','80','','','0'),
('QC1','ctqc','pass','20','Pass','Pass','0','0','0','CHECKBOX','60','','','0'),
('QC1','ctqc','ma_nv','21','Người kiểm tra','Người kiểm tra','0','0','0','','80','','','0'),
('QC1','ctqc','ket_qua_qc','22','Kết luận','Kết luận','0','1','0','','160','','','0'),
('QC1','ctqc','muc_dich_sd','23','Mục đích sử dụng','Mục đích sử dụng','0','0','1','','100','','','0'),
('QC1','ctqc','sl_nhap','24','SL cho phép nhập','SL cho phép nhập','0','1','1','SL','80','','','0'),
('QC1','ctqc','sl_tra','25','SL trả về','SL trả về','0','1','1','SL','80','','','0'),
('QC1','ctqc','category','26','Category','Category','0','0','0','','200','','','0'),
('QC1','ctqc','nguyen_nhan','27','Nguyên nhân lỗi','Cause Errors','0','0','0','','200','','','0'),
('QC1','ctqc','bien_phap','28','Biện pháp xử lý','Treatment measures','0','0','0','','200','','','0'),
('QC1','ctqc','kiem_soat','29','Kiểm soát','Control','0','0','0','','200','','','0'),
('QC1','ctqc','chap_nhan_db','30','Chấp nhận đặc biệt bởi','Special acceptance by','0','0','0','','200','','','0'),
('QC1','ctqc','ghi_chu','31','Ghi chú','Ghi chú','0','1','0','','200','','','0'),
('QC1','ctqc','so_ct_pr1','32','Số phiếu nhập','Import votes','0','1','0','','100','','','0'),
('QC1','ctqc','so_ct_pnd','33','Số phiếu nhập GC','Import votes GC','0','1','1','','100','','','0'),
('QC1','ctqc','so_ct_pxe','34','Số phiếu xuất tách','Number of votes split','0','0','1','','100','','','0'),
('QC1','ctqc','po_khsx','5','PO KHSX','PO KHSX','0','1','1','','200','','','0'),
('QC1','ctqc','dau_tuan','6','Dấu tuần','Dấu tuần','0','1','1','','200','','','0'),
('QC1','ctloqc1','po_khsx','4','PO KHSX','PO KHSX','0','1','1','MA','100','','','0'),
('QC1','ctloqc1','dau_tuan','5','Dấu tuần','Dấu tuần','0','1','1','MA','100','','','0');

COMMIT;
