BEGIN;

DELETE FROM repinfo WHERE form = 'PORequest2';

INSERT INTO repinfo (form,name,type,val,val2,df,df2) VALUES
('PORequest2','h_slduyet','C','SL duyệt','Total                                                           ','SL duyệt','Total                                                           '),
('PORequest2','s_thu_kho','C','Thủ kho                                                         ','Storekeeper                                                     ','Thủ kho                                                         ','Storekeeper                                                     '),
('PORequest2','f_ong_ba','F','Ong_ba','Ong_ba','Ong_ba','Ong_ba'),
('PORequest2','c_dia_chi','C','Địa chỉ                                                         ','Address                                                         ','Địa chỉ                                                         ','Address                                                         '),
('PORequest2','c_dien_giai','C','Diễn giải                                                       ','Description                                                     ','Diễn giải                                                       ','Description                                                     '),
('PORequest2','c_kh','C','Đơn vị                                                          ','Company                                                         ','Đơn vị                                                          ','Company                                                         '),
('PORequest2','c_ong_ba','C','Người nhận hàng                                                 ','Receiver                                                        ','Người nhận hàng                                                 ','Receiver                                                        '),
('PORequest2','f_dien_giai','F','Dien_giai                                                       ','Dien_giai                                                       ','Dien_giai                                                       ','Dien_giai                                                       '),
('PORequest2','f_tk_no','F','Ma_nx                                                           ','Ma_nx                                                           ','Ma_nx                                                           ','Ma_nx                                                           '),
('PORequest2','h_dvt','C','Đvt                                                             ','Uom                                                             ','Đvt                                                             ','Uom                                                             '),
('PORequest2','h_gia','C','Giá                                                             ','Price                                                           ','Giá                                                             ','Price                                                           '),
('PORequest2','h_ma_kho','C','Kho                                                             ','Site                                                            ','Kho                                                             ','Site                                                            '),
('PORequest2','h_ma_vt','C','Mã vt                                                           ','Item id                                                         ','Mã vt                                                           ','Item id                                                         '),
('PORequest2','h_so_luong','C','Sl                                                              ','Q.ty                                                            ','Sl                                                              ','Q.ty                                                            '),
('PORequest2','h_stt','C','Tt                                                              ','No                                                              ','Tt                                                              ','No                                                              '),
('PORequest2','h_ten_vt','C','Tên vật tư                                                      ','Item name                                                       ','Tên vật tư                                                      ','Item name                                                       '),
('PORequest2','h_tien','C','Tiền                                                            ','Amount                                                          ','Tiền                                                            ','Amount                                                          '),
('PORequest2','h_tk_co','C','Tk có                                                           ','Cr                                                              ','Tk có                                                           ','Cr                                                              '),
('PORequest2','h_tk_no','C','Mã nx                                                           ','Reason                                                          ','Mã nx                                                           ','Reason                                                          '),
('PORequest2','s_Amount','C','Tiền hàng                                                       ','Amount                                                          ','Tiền hàng                                                       ','Amount                                                          '),
('PORequest2','s_giao_hang','C','Người giao hàng                                                 ','Receiver                                                        ','Người giao hàng                                                 ','Receiver                                                        '),
('PORequest2','s_nhan_hang','C','Người xuất                                                      ','Deliverer                                                       ','Người xuất                                                      ','Deliverer                                                       '),
('PORequest2','s_nhap_hang','C','Pt xuất hàng                                                    ','Admin                                                           ','Pt xuất hàng                                                    ','Admin                                                           '),
('PORequest2','s_Tax','C','Thuế                                                            ','Tax                                                             ','Thuế                                                            ','Tax                                                             '),
('PORequest2','s_total','C','Tổng cộng                                                       ','Total                                                           ','Tổng cộng                                                       ','Total                                                           '),
('PORequest2','h_slyeucau','C','SL yêu cầu','Total                                                           ','Tổng cộng                                                       ','Total                                                           '),
('PORequest2','c_nguoiyeucau','C','Người yêu cầu','Total                                                           ','Tổng cộng                                                       ','Total                                                           '),
('PORequest2','c_nhacc','C','Nhà cung cấp','Total                                                           ','Tổng cộng                                                       ','Total                                                           '),
('PORequest2','c_giaodich','C','Giao dịch','Total                                                           ','Tổng cộng                                                       ','Total                                                           '),
('PORequest2','h_xuat_tra','C','Đồng ý xuất trả','Export applier','Tổng cộng                                                       ','Total                                                           '),
('PORequest2','h_nguoi_lap','C','Người lập biểu','Creator','Tổng cộng                                                       ','Total                                                           '),
('PORequest2','s_ck','C','Chiết khấu','Discount','Tổng cộng                                                       ','Total                                                           '),
('PORequest2','h_xac_nhan_ncc','C','Xác nhận của NCC','Suplier confirm','Tổng cộng                                                       ','Total                                                           '),
('PORequest2','h_thu_kho','C','Thủ kho xuất','Storekeeper confirm','Tổng cộng                                                       ','Total                                                           '),
('PORequest2','h_dau_tuan','C','Dấu tuần','Dấu tuần','Dấu tuần','Dấu tuần'),
('PORequest2','h_po_khsx','C','PO KHSX','PO KHSX','PO KHSX','PO KHSX');

COMMIT;
