-- Type: public.potranstatus_return

 DROP TYPE public.potranstatus_return cascade;

CREATE TYPE public.potranstatus_return AS
   (sysorder smallint,
    sysprint smallint,
    systotal smallint,
    stt smallint,
    ma_dvcs character varying,
    stt_rec public.ud_stt_rec,
    ngay_ct public.ud_ngay,
    so_ct public.ud_so_ct,
    ma_kh character varying,
    ten_kh character varying,
    ten_kh2 character varying,
    ma_vt character varying,
    ten_vt character varying,
    so_luong public.ud_float,
    gia public.ud_float,
    gia_nt public.ud_float,
    tien public.ud_float,
    tien_nt public.ud_float,
    thue public.ud_float,
    thue_nt public.ud_float,
    ck public.ud_float,
    ck_nt public.ud_float,
    so_luong_01 public.ud_float,
    chenh_lech_01 public.ud_float,
    stt_rec_01 character varying,
    so_ct_01 character varying,
    ngay_ct_01 public.ud_ngay,
    so_luong_12 public.ud_float,
    chenh_lech_12 public.ud_float,
    stt_rec_12 character varying,
    so_ct_12 character varying,
    ngay_ct_12 public.ud_ngay,
    group_code character varying,
    stt_rec_pr1 character varying,
    ngay_nh_po1 public.ud_ngay,
    ngay_nh_pr1 public.ud_ngay,
    cl_ngay integer,
    dvt character varying,
    tt_dh character varying,
    status character varying,
    ghi_chu character varying,
    user_id integer,
    user_name character varying,
    muc_dich_sd character varying,
    dien_giai character varying,
    so_ct_pr0 character varying,
    so_ct_dhb public.ud_so_ct,
    po_khsx character varying,
    dau_tuan character varying);
ALTER TYPE public.potranstatus_return
  OWNER TO postgres;
