-- Type: public.sobk12_return

 DROP TYPE public.sobk12_return cascade;

CREATE TYPE public.sobk12_return AS
   (sysorder public.ud_smallint,
    sysprint public.ud_smallint,
    systotal public.ud_smallint,
    ma_vt character varying,
    dvt character varying,
    sl_nhap public.ud_float,
    sl_xuat public.ud_float,
    gia_nt2 public.ud_float,
    tien_nt2 public.ud_float,
    tien_nt_x public.ud_float,
    tien_nt_n public.ud_float,
    thue_nt public.ud_float,
    ck_nt public.ud_float,
    gia_nt public.ud_float,
    gia2 public.ud_float,
    tien2 public.ud_float,
    tien_xuat public.ud_float,
    tien_nhap public.ud_float,
    thue public.ud_float,
    ck public.ud_float,
    gia public.ud_float,
    ma_nx character varying,
    ma_kho character varying,
    ma_vv character varying,
    ma_ct character varying,
    dien_giai character varying,
    dien_giai2 character varying,
    stt_rec character varying,
    ln smallint,
    ngay_ct pg_catalog.date,
    so_ct character varying,
    pt public.ud_float,
    pt_nt public.ud_float,
    so_luong public.ud_float,
    tien public.ud_float,
    tien_nt public.ud_float,
    ma_kh character varying,
    ten_kh character varying,
    ten_kh2 character varying,
    ten_vt character varying,
    ten_vt2 character varying,
    mau_hd public.ud_ten,
    so_seri character varying,
    so_hd character varying,
    rp_group character varying,
    ma_nt public.ud_ma_nt,
    ty_gia public.ud_float,
    gio_gh public.ud_time,
    sl_duyet public.ud_float,
    tien2_closing public.ud_float,
    thue_closing public.ud_float,
    ck_closing public.ud_float,
    pt_closing public.ud_float,
    so_po character varying,
    model character varying,
    so_ecis character varying);
ALTER TYPE public.sobk12_return
  OWNER TO postgres;
